### ISSUE TITLE
Pedido de Compras - Frete

### ISSUE THREAD

**Issue by razielucas** [razielucas/Maldonado#2]
Frete
		* Trazer da tabela de preços ao gerar o pedido de compras;
		* Criar uma aba (ou campo) com os dados da transportadora na tela de pedidos de compras.

**Comment by razielucas** [comment]
Alterados os pontos de entrada para aplicação das alterações na rotina.


MT120CPE
------------
	Solicitante: Edilson / Paula | Analista: Lucas - MLD | Data: 31/08/2015 - Adicionada nova aba para exibição de informações

MT120SCR
-------------
	Solicitante: Edilson / Paula | Analista: Lucas - MLD | Data: 31/08/2015 - Adicionado exibição de dados da transportadora de acordo com a tabela de preços.

MT120GOK
-------------
	Solicitante: Edilson / Paula | Analista: Lucas - MLD | Data: 31/08/2015 - Adicionado tratamento para repassar o tipo de frete do cadastro de Tabelas de Preços.

**Comment by franciscpd** [comment]
Bom dia, é possível me encaminhar um exemplo de utilização do ponto de entrada MT120CPE? Desde já agradeço a atenção.
